# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: fulin87的笔记
email: fulin87@sina.com
description1: 唯天下之至诚，胜天下之至伪
description2: 唯天下之至拙，胜天下之至巧
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://colorful.ren" # the base hostname & protocol for your site
twitter_username: fulin87
github_username:  fulin87

# Build settings
markdown: kramdown
destination: E:\home\mine\study\git\bolg